<a href="https://colab.research.google.com/github/bhagich/ML/blob/main/Titanic_Logistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import files
uploaded = files.upload()

Saving titanic_cleaned.csv to titanic_cleaned.csv


In [21]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

In [7]:
titanic = pd.read_csv('titanic_cleaned.csv')

In [9]:
titanic.shape

(891, 15)

In [10]:
titanic.isnull().sum()

Unnamed: 0       0
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
Cabin_ind        0
Family_Cnt       0
dtype: int64

In [12]:
col_needed=['Pclass','Sex','Age','Cabin_ind','Fare','Family_Cnt']
X = titanic[col_needed]
y = titanic['Survived']

In [13]:
X.shape

(891, 6)

In [14]:
X.head()

Pclass     Sex   Age  Cabin_ind     Fare  Family_Cnt
0       3    male  22.0          0   7.2500           1
1       1  female  38.0          1  71.2833           1
2       3  female  26.0          0   7.9250           0
3       1  female  35.0          1  53.1000           1
4       3    male  35.0          0   8.0500           0

In [17]:
#Create Dummies for Qualitative/Categorical Variables
X = pd.get_dummies(X, columns=['Pclass','Sex'])

In [18]:
X.head()

Age  Cabin_ind     Fare  Family_Cnt  Pclass_1  Pclass_2  Pclass_3  \
0  22.0          0   7.2500           1         0         0         1   
1  38.0          1  71.2833           1         1         0         0   
2  26.0          0   7.9250           0         0         0         1   
3  35.0          1  53.1000           1         1         0         0   
4  35.0          0   8.0500           0         0         0         1   

   Sex_female  Sex_male  
0           0         1  
1           1         0  
2           1         0  
3           1         0  
4           0         1

In [19]:
X.drop('Sex_female',axis=1,inplace=True)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [23]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()
reg.fit(X_train, y_train)

LogisticRegression()

In [24]:
reg.coef_

array([[-0.04068118,  0.73280686,  0.00281657, -0.24405836,  1.06037351,
         0.71866065, -0.28347034, -2.59760352]])

In [25]:
pred = reg.predict(X_test)

In [26]:
pred

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0])

In [27]:
reg.predict_proba(X_test)

array([[0.88555908, 0.11444092],
       [0.88751627, 0.11248373],
       [0.90901902, 0.09098098],
       [0.05974873, 0.94025127],
       [0.47652096, 0.52347904],
       [0.48109081, 0.51890919],
       [0.06910256, 0.93089744],
       [0.07511203, 0.92488797],
       [0.45179868, 0.54820132],
       [0.37026463, 0.62973537],
       [0.89644512, 0.10355488],
       [0.2440846 , 0.7559154 ],
       [0.88746002, 0.11253998],
       [0.1169024 , 0.8830976 ],
       [0.04506923, 0.95493077],
       [0.23658384, 0.76341616],
       [0.85672762, 0.14327238],
       [0.73771141, 0.26228859],
       [0.90719493, 0.09280507],
       [0.75321716, 0.24678284],
       [0.64024505, 0.35975495],
       [0.06948515, 0.93051485],
       [0.88746353, 0.11253647],
       [0.65829958, 0.34170042],
       [0.29908949, 0.70091051],
       [0.113143  , 0.886857  ],
       [0.8964369 , 0.1035631 ],
       [0.30032352, 0.69967648],
       [0.17752753, 0.82247247],
       [0.37851796, 0.62148204],
       [0.

In [28]:
print('training accuracy', reg.score(X_train, y_train))

training accuracy 0.8075842696629213


In [29]:
print('test accuracy', reg.score(X_test, y_test))

test accuracy 0.8379888268156425
